services:
  migrate:
    image: migrate/migrate
    volumes:
      - ./scripts/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://root:root@192.168.0.100:5432/agency_v3?sslmode=disable", "up"]
    healthcheck:
      test: "exit 0"

